sudo: required

language: generic

services:
  - docker

stages:
  - qa

jobs:
  include:
    - stage: qa
      script: make run-in-docker cmd="make codequality"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - curl -XPOST https://goreportcard.com/checks -F 'repo=github.com/opsway/documents
